apiVersion: apps/v1
kind: Deployment
metadata:
  name: e1stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: e1stream
    spec:
      containers:
        - name: e1stream
          image: aelmendorf234/monitoringdatadataloggingservice:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
            - name: DEVICEID
              value: epi1
            - name: SERVICE_TYPE
              value: MonitorBox
  selector:
    matchLabels:
      app: e1stream
---
apiVersion: v1
kind: Service
metadata:
  name: e1stream
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: e1stream