apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhstream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nhstream
    spec:
      containers:
        - name: nhstream
          image: aelmendorf234/monitoringdatadataloggingservice:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
            - name: DEVICEID
              value: nh3
            - name: SERVICE_TYPE
              value: GenericModbus
  selector:
    matchLabels:
      app: nhstream
---
apiVersion: v1
kind: Service
metadata:
  name: nhstream
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nhstream